### PR TITLE
fix bug of copy multipart. Issue #178

### PR DESCRIPTION
**Pull request by Zstro**

### CODE REVIEW

**Comment by thesues** [comment]
Can you add a new test case for it?

**Comment by Zstro** [comment]
> Can you add a new test case for it?

I have added it in anyother pr. #177

**Comment by cannium** [comment]
Could you explain why this change works? I can't tell from code diff.

**Comment by Zstro** [comment]
> Could you explain why this change works? I can't tell from code diff.

Because part.Etag is compared with calculatedMd5,part should be in order.

**Pull request closed without merging**
